### PR TITLE
Add bus output "KynDynOut" to "Robot" library for exporting the kinematic & dynamic variables

### PR DESCRIPTION
**Pull request by nunoguedelha**
- Add 'getFeetContactState()' to class 'Contacts'.
- Add 'kinDynOut' to 'stepImpl() method of matlab.system class step_block.
- Assign 'kinDynOut' structure with computed kinematic and dynamic variables.
- Set new 'kinDynOut' output size, type, "complexity" properties.
  Note: the type 'obj.OutputBusName' is a string set through the Matlab System
  block interface. It is set to 'kinDynOut_bus', a bus object (Simulink.Bus)
  created in the workspace by the library init script. Each element of the bus
  Simulink.BusElement implements a signal with the properties: Name, Dimensions,
  Datatype, Complexity. For instance a wrench will have Dimensions=[6,1].
- Updated the test model for exposing the output bus signals through a bus selector.
- Added .gitattributes for activating the Simulink model diff from terminal feature.
- For this Simulink model diff to work from the terminal, add the following blob to
  your local git config (<repo path>/.git/config) or your global config (~/.gitconfig):
```
[diff "matlabSource"]
        xfuncname = matlab
[diff "matlabModel"]
        command = git diffMatlabModel
[alias]
        diffMatlabModel = "!f() { ext=`echo "$2" | cut -d'.' -f2`; cp $2 filediff1.${ext}; cp $5 filediff2.${ext}; matlab -nodesktop -r \"visdiff('filediff1.${ext}','filediff2.${ext}')\";}; f"
```
- for running the Simulink model diff from the terminal, do:
```
> git diff <commit1> <commit2> <filrname>
```

For more details/example on how to setup an output bus from a Matlab.system block, please refer to https://www.mathworks.com/help/simulink/slref/using-buses-with-matlab-system-blocks.html.
For understanding how to create a bus programmatically, refer to https://www.mathworks.com/help/simulink/ug/create-bus-objects-programmatically.html.

### CODE REVIEW

**Comment by nunoguedelha** [comment]
## How to validate this PR
- run the test script `test_matlab_system_19.mdl` as usual, with its default parameters.
- pause the simulation and open the bus selector connected to the output `kynDynOut` in the main model. You should see the list of the full list of available kinematic and dynamic variables as shown below:

image

**Comment by nunoguedelha** [comment]
ciao @Giulero , can I merge this? I don't know if you had time to review it...

**Review by Giulero — APPROVED** [review]

**Comment by Giulero** [comment]
Ciao @nunoguedelha! Test is done. 
This is an amazing feature!

**Comment by nunoguedelha** [comment]
Yes! It should unlock a lot of possibilities for implementing interfaces, while reducing the clutter of connecting signals. Thanks for the tests.

**Pull request merged**
