### PR TITLE
Add motor reflected inertas

### PR DESCRIPTION
**Pull request by nunoguedelha**
This PR adds the motor reflected inertias to the robot dynamics simulation.

## Motivation and Rational

In case of a humanoid robot, the joint space mass matrix can be ill conditioned, which can lead to numerical instability of the simulation if the matrix needs to be inverted (this problem is typically agravated in the case of robots of small dimensions). For solving this problem, the motors dynamics can then be introduced in the floating base system dynamics and the respective rotor inertias can be reflected in the robot mass matrix. The so called reflected inertias may be interpreted as a physically consistent regularization term for the original mass matrix [1].

The motor coupling is defined as follows:

\begin{aligned}
\dot{s} &= \Gamma \dot{\theta} \\\\
\tau &= \Gamma^{-\top} \left( \tau_m + \tau_f \right)
\end{aligned}

Where $\dot{\theta}$, $\tau_m$, $\dot{s}$, $\tau$ are respectively the motor velocity and torque, the joint velocity and torque, $\Gamma$ is the transfer matrix of a frictionless [gearbox + coupling] system. $\tau_f$ is the friction in the that gearbox and coupling system, grouped in a single component, expressed in the motor space, and which could typically be approximated to a Coulomb/Viscous model ( $\tau_f = -K_{v} \dot{\theta} -K_{c} \operatorname{sign}(\dot{\theta})$ ). Here we will keep the friction as a generic term.  The motor dynamics in motor space is then posed as follows:

\begin{equation}
I_{m} \ddot{\theta} = \tau_m+\tau_f-\Gamma^{\top} \tau
\end{equation}

Where $I_m$ is the diagonal matrix of motor inertias (in the motor space), and $\ddot{\theta}$ the vector of motor accelerations. In joint space we can write:
\begin{aligned}
\Gamma^{-\top} I_{m} \Gamma^{-1} \ddot{s} &= \Gamma^{-\top} \left( \tau_m+\tau_f \right) - \tau \\\\
\tau &= \Gamma^{-\top} \left( \tau_m+\tau_f \right) - \Gamma^{-\top} I_{m} \Gamma^{-1} \ddot{s}
\end{aligned}

Once replaced in the floatng system equations, we get the modified mass matrix:

\begin{equation}
\overline{M}=\left[\begin{array}{cc}
M_{b} & 0_{6 \times n} \\\\
0_{n \times 6} & \overline{M}_{s}
\end{array}\right]
\end{equation}

With $\overline{M}_{s} = M_s + \Gamma^{-\top} I_{m} \Gamma^{-1}$.

and

\begin{equation}
\overline{M}=
M + 
\begin{bmatrix}
0_{6 \times 6} & 0_{6 \times n} \\\\
0_{n \times 6} & \Gamma^{-\top} I_{m} \Gamma^{-1}
\end{bmatrix}
\end{equation}

### References
[1] A. Albu-Schäffer, C. Ott, and G. Hirzinger, “A unified passivity-based control framework for position, torque and impedance control of flexible joint robots,” Int. J. Rob. Res., vol. 26, no. 1, pp. 23–39, 2007.
[2] A. Albu-Schäffer, C. Ott, and G. Hirzinger, “A unified passivity-based control framework for position, torque and impedance control of flexible joint robots,” Int. J. Rob. Res., vol. 26, no. 1, pp. 23–39, 2007.

## Interface Changes

- New library input parameter `robot_config.SIMULATE_MOTOR_REFLECTED_INERTIA`: this new field in the `robot_config` input structure toggles ON/OFF the feature. For making sure that the simulation of the reflected inertia is seen as a parameter independent from what a given driving controller is doing (using or not reflected inertia), I named the parameter "SIMULATE_MOTOR_REFLECTED_INERTIA" and not "USE_MOTOR_REFLECTED_INERTIA". The parameter is stored in the class `Robot`.
- New library input parameter `config.MOTOR_REFLECTED_INERTIA_COUPLING`: this new field in the `robot_config` input structure sets the coupling matrix $\Gamma$, as explaned in [this section](#motivation-and-rational), except that we split the overall coupling in a pure coupling $\Gamma$ and the gearbox ratios $G$ (for instance, for iCub, $G=1/100$), such that:

\begin{equation}
\dot{s} = \Gamma G \dot{\theta}
\end{equation}

- Input signal `motorInertias`: This represents the quantity $\Gamma^{-\top} G^{-1} I_{m} G^{-1} \Gamma^{-1}$, while the input joint torques signal `torque` represents $\Gamma^{-\top} G^{-1} \left( \tau_m + \tau_f \right)$, as the friction and the coupling could be computed in a dedicated joint/motor model block, as explaned in https://github.com/dic-iit/matlab-whole-body-simulators/pull/9#issuecomment-724104865.

## Implementation Changes

Every use or retrieval of the mass matrix $M$ uses $\overline{M}$ instead, defined by:

\begin{equation}
\overline{M}=
M + 
\begin{bmatrix}
0_{6 \times 6} & 0_{6 \times n} \\\\
0_{n \times 6} & \Gamma^{-\top} G^{-1} I_{m} G^{-1} \Gamma^{-1}
\end{bmatrix}
\end{equation}

### CODE REVIEW

**Comment by traversaro** [comment]
Preliminary comment, ignore if it will be changed: there is any specific reason not to make the `motorInertias` an attribute of the Robot class?

**Comment by nunoguedelha** [comment]
> Preliminary comment, ignore if it will be changed: there is any specific reason not to make the `motorInertias` an attribute of the Robot class?

It's a good point @traversaro . There was not particular reason, except that:
- I had in mind that `motorInertias` is an input that can be porvided for instance by an external block modelling the joint actuation motors/gearboxes/couplings. Actually I made a mistake, as that external block would already compute the product $\Gamma^{-\top} I_{m} \Gamma^{-1}$, then sent to the `step_block` of the **robotDynamicsWithContacts** library as the `motorInertias` input.
- Having that in consideration, in a near future, we will have to deal with backlash. In that case, when the motor shaft is in the dead zone gap, the torque is not transmitted and the rotor inertia is not reflected in the robot mass matrix. When that happens, the resulting effect in the joint space depends on the coupling and where the backlash occurs (before or after the coupling). So the safest way to go, for avoiding interface changes, would be to compute  $\Gamma^{-\top} I_{m} \Gamma^{-1}$ in the joint model.
- As `motorInertias` is never changed by the functions using it, MATLAB/SIMULINK optimization avoids to copy the variable and so kind of uses the same variable allocated in the memory. So I didn't consider that having `motorInertias` as an attribute would improve the performance.
- We could pose the same question about the joint torques, which could also be properties of the robot.

In addition, I thought about addressing this a bit later when optimizing the code. Typically, `robot.get_mass_matrix(motorInertias)` is called a total of 3 times, and every time the iDynTree binding `KinDynModel.kinDynComp.getFreeFloatingMassMatrix()` is called, which is a priori sub-optimal.

What do you think?

**Comment by traversaro** [comment]
> What do you think?

If motorInertia are not constant and instead it is an input, then I totally agree in it not being an attribute of the class.

**Comment by nunoguedelha** [comment]
Great. Then maybe we should call the input `jointInertias`, as the variable part, and a parameter `motorInertias` as a property of the class Robot, representing the vector of fixed motor inertias in the motor space. Then, an hypothetical joint model block should retrieve those parameters from the class at the initialization of the simulation, instead of getting those from some configuration script.
I'll leave this change for the next PR.

**Comment by DanielePucci** [comment]
As a word of clarification, Eq. (1) holds if the angular motor kinetic energy is due to its own spinning only, and the center of mass of each motor is along the motor axis of rotation. Otherwise, off-diagonal terms in (2) are present.

**Comment by nunoguedelha** [comment]
For avoiding confusion, removed motor coupling parameter `Robot.MOTOR_REFLECTED_INERTIA_COUPLING` since it is not used yet. PR is ready for review.

**Comment by nunoguedelha** [comment]
## How to validate this PR
- run the test script `test_matlab_system_19.mdl` as usual, with its default parameters. => You should observe the same usual behavior of iCub.

New default parameter in `configRobot.m`:
```
% Reflected inertia
Config.SIMULATE_MOTOR_REFLECTED_INERTIA = true;
```

Future tests will further stress the motor reflected inertia feature when a simple controller will be added to the tester model.

**Comment by Giulero** [comment]
Great @nunoguedelha, everything's smooth!

**Review by Giulero — APPROVED** [review]

**Pull request merged**
